name: Upload Python Package

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build package
    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.10
        cache: true
        cache-dependency-path: |
          ./pdm.lock
    - name: Install dependencies
      run: |
        pdm install
      env:
        PDM_USE_VENV: "0"
    - name: Build package
      run: pdm build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish:
    name: Publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/restic-airflow
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

